### ISSUE TITLE
Jungle Reset Survey 

### ISSUE THREAD

**Issue by xavier506** [EOS-Jungle-Testnet/jungletestnet.io#1]
In a recent Jungle community [open weekly call](https://github.com/EOS-Jungle-Testnet/jungletestnet.io/blob/master/README.md) the possibility of resetting the jungle testnet and starting a new blockchain was discussed. 

Since there are many different stakeholders using Jungle Testnet this decision should be a community driven initiative , which is why we need to create a survey to gauge community sentiment. 

Google forms was suggested as a posible tools for this job.

**Comment by xavier506** [comment]
I created an initial survey using google forms in the following URL : https://goo.gl/forms/26cAfh8Re0q4Py503

@ansigroup please review and let me know your thoughts. 

It may be good to specify some of the pros and cons of resetting the Jungle

**Pros:**
 - new blockchain will eliminate "poisoned blocks" which is a barrier to entry for new users
 - syncing new nodes will require less time for new nodes to get up and running
 - ?

**Cons:** 
- potential accounts and balances lost
- contracts code will require migration
- table data loss
- ?

**Comment by gaboesquivel** [comment]
Results of the Survey can be found here
https://medium.com/jungletestnet/next-steps-for-the-jungle-testnet-ca856d0c7b58
